// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyERP.Infrastructure.EFCore;

namespace MyERP.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("MyERP.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2203c8e5-21a4-48e0-b17a-08b00d3e1702"),
                            Date = new DateTime(2021, 1, 27, 0, 0, 0, 0, DateTimeKind.Local),
                            Price = 500m
                        },
                        new
                        {
                            Id = new Guid("7a209cc2-88be-4b4d-bbd6-7106a3c6f8f5"),
                            Date = new DateTime(2021, 1, 27, 0, 0, 0, 0, DateTimeKind.Local),
                            Price = 500m
                        },
                        new
                        {
                            Id = new Guid("3a38da79-7340-4e18-ad9d-faea343aa20e"),
                            Date = new DateTime(2021, 1, 27, 0, 0, 0, 0, DateTimeKind.Local),
                            Price = 500m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
